version: '3.8'

services:

  # Serviço 1: Servidor Web (Apache + PHP)
  webserver:
    build: .
    container_name: paradesporto-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

  # Serviço 2: Banco de Dados (MySQL)
  database:
    image: mysql:8.0
    container_name: paradesporto-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paradesporto_db
    ports:
      - "127.0.0.1:33066:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

  # Serviço 3: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: database   # usa o nome do serviço do MySQL
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  db-data:
